name: semi_ecommerce_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  carousel_slider: ^4.2.1
  badges: ^3.1.1

  # Network
  dio: 4.0.4
  logger: 1.1.0
  sprintf: 6.0.0
  sms_autofill: 2.2.0
  pin_code_fields: 7.3.0
  firebase_messaging: 14.6.3
  firebase_core: 2.14.0
  firebase_remote_config: 4.2.3
  cloud_firestore: 4.8.1
  #  webview_flutter: ^3.0.4
  url_launcher: 6.1.5
  flutter_local_notifications: 12.0.0

  # local storage
  cached_network_image: 3.1.0+1
  hive: 2.2.1
  hive_flutter: 1.1.0

  # state management
  get_it: 7.2.0
  injectable: 1.5.0
  injectable_generator: 1.5.2

  #UI
  persistent_bottom_nav_bar: 4.0.2
  image_picker: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_native_splash: any
  #  flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: 0.9.2


flutter:


  uses-material-design: true
  generate: true


  assets:
    - assets/images/


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo3.png
  android: true
  ios: true
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/images/avatar1.jpg

    # Splash screen background color.
    color: "#FFFFFF"

  # App icon background color.
  #icon_background_color: "#111111"

  # The branding property allows you to specify an image used as branding in the splash screen.

  # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
  # apply when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above.
  #image_dark: assets/android12splash-invert.png
  #color_dark: "#042a49"
  #icon_background_color_dark: "#eeeeee"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo3.png"
